EBODAC-1189: Add ability to ignore date limits on Clinic Visit Schedule tab
motech-implementations/prevac pull request #48
Opened 2018-02-14 17:56 UTC by kcissewski

2018-02-15 14:41 UTC, pmuchowski requested changes

2018-02-15 14:41 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +                    earliestDate = visitDates.get(PRIME_VAC_DATE_KEY).plusDays(PrevacConstants.EARLIEST_DATE_IF_FEMALE_CHILD_BEARING_AGE);
you should not modify the planned date

2018-02-15 14:41 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
>                  if (subject.getFemaleChildBearingAge() == null || !subject.getFemaleChildBearingAge()) {
I think you should add one more if (plannedDate != null) and set earliestDate = plannedDate there, ale else if the rest without change

2018-02-15 14:41 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +            if (subject.getFemaleChildBearingAge() == null || !subject.getFemaleChildBearingAge()) {
you should update the validation, according to my previous comments

2018-02-15 14:41 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +        if (!datesMap.containsKey(PRIME_VAC_DATE_KEY)) {
I don't think it should be required, we can use screening date if it's null (like it was done before)

2018-02-15 14:41 UTC, pmuchowski commented on src/main/resources/webapp/js/controllers.js
> +                                if (date < now) {
I'm not sure if we should display 2 separate confirmation messages

2018-02-16 10:03 UTC, kcissewski commented
@pmuchowski  fixed issues that you've pointed.

2018-02-16 11:08 UTC, pmuchowski requested changes

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +                earliestDate = primeVacPlannedDate.plusDays(PrevacConstants.EARLIEST_DATE_IF_FEMALE_CHILD_BEARING_AGE);
why are you changing the planned date here, when user was choosing it FemaleChildBearingAge was already checked, so you should **not** add it to planned date here

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +    private LocalDate setEarliestDate(Map<String, LocalDate> dateMap, Subject subject) {
I think you should name this method getEarliestDate and add as a parameters screeningDate and plannedDate separately not in the map, it will simplify the code

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +                latestDate = visitDates.get(SCREENING_DATE_KEY).plusDays(PrevacConstants.LATEST_DATE);
if only prime planned date is in the map, you will get a null pinter exception here

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +            Map<String, LocalDate> visitDates = getScreeningAndPrimeVacDates(subject);
I think you should get the dates from the map here

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +            if (!visitDates.isEmpty()) {
getScreeningAndPrimeVacDates is throwing an exception if screening date is empty

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +        } else if (dateMap.containsKey(SCREENING_DATE_KEY)) {
you can remove this if, because screening date will be checked already

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +            LocalDate earliestDate;
you should use the getEarliestDate method here too

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +        if (datesMap.isEmpty()) {
remove this, you are already checking the screening below

2018-02-16 11:08 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +            if (!visitDates.containsKey(SCREENING_DATE_KEY)) {
it's already checked in getScreeningAndPrimeVacDates

2018-02-16 11:25 UTC, kcissewski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +                earliestDate = primeVacPlannedDate.plusDays(PrevacConstants.EARLIEST_DATE_IF_FEMALE_CHILD_BEARING_AGE);
Oh, I misunderstood your previous comment. Silly me. Thank you!

2018-02-16 12:03 UTC, pmuchowski requested changes

2018-02-16 12:03 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +            earliestDate = primeVacPlannedDate;
you can just return the primeVacPlannedDate here

2018-02-16 12:03 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +                earliestDate = screeningDate;
return the screening here

2018-02-16 12:03 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +                earliestDate = screeningDate.plusDays(PrevacConstants.EARLIEST_DATE_IF_FEMALE_CHILD_BEARING_AGE);
and return this at the end

2018-02-16 12:03 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +        } else {
no need for "else" then

2018-02-16 12:03 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +            } else {
you can also remove this "else"

2018-02-16 12:03 UTC, pmuchowski commented on src/main/java/org/motechproject/prevac/service/impl/VisitScheduleServiceImpl.java
> +        LocalDate earliestDate = null;
this variable will not be needed

2018-02-16 12:17 UTC, pmuchowski approved these changes

2018-02-16 12:39 UTC, merged